/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import java.awt.Dimension;
import java.awt.GridLayout;
import javax.swing.JOptionPane;
import java.util.Date;


/**
 *
 * @author azalia
 */
public class Juego extends javax.swing.JFrame {
    Player datos;
    Login1 login;
    Menu1 menu;
    Usuarios1 usuarios;
    
   
    /**
     * Creates new form Juego
     */
    public Juego(Login1 login,Player datos) {
        initComponents();
        this.datos = datos;
        this.login = login;
        
        //definir tamano y centrar el tablero
        this.setSize(1200, 650);
        this.setLocationRelativeTo(this);
        setVisible(true);
       
         setTitle("Ghosts - En Partida");
        Tablero.setLayout(new GridLayout(1,1));
        Tablero.setMinimumSize(new Dimension(500, 100));
        Tablero.add(new TableroGhost(datos, login, txtAreaEliminados,lblTurnos1, this));  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Eliminados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEliminados = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblTurnos1 = new javax.swing.JLabel();
        btnRetiro = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTurnos = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Tablero = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Marvel Stratego - En Partida");
        setSize(new java.awt.Dimension(0, 0));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Eliminados.setLayout(null);

        txtAreaEliminados.setColumns(20);
        txtAreaEliminados.setRows(5);
        jScrollPane1.setViewportView(txtAreaEliminados);

        Eliminados.add(jScrollPane1);
        jScrollPane1.setBounds(60, 80, 234, 370);

        jLabel4.setBackground(new java.awt.Color(19, 153, 242));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Datos De Tus Personajes-Ghost");
        Eliminados.add(jLabel4);
        jLabel4.setBounds(30, 50, 290, 16);

        lblTurnos1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblTurnos1.setForeground(new java.awt.Color(255, 255, 255));
        lblTurnos1.setText("jLabel5");
        Eliminados.add(lblTurnos1);
        lblTurnos1.setBounds(50, 490, 250, 22);

        btnRetiro.setBackground(new java.awt.Color(153, 153, 0));
        btnRetiro.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnRetiro.setText("RETIRO");
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });
        Eliminados.add(btnRetiro);
        btnRetiro.setBounds(40, 10, 120, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fantasmas fondo menus1.png"))); // NOI18N
        Eliminados.add(jLabel2);
        jLabel2.setBounds(10, 0, 320, 610);

        lblTurnos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTurnos.setForeground(new java.awt.Color(255, 255, 255));
        lblTurnos.setText("Turno de: ");
        lblTurnos.setToolTipText("");
        Eliminados.add(lblTurnos);
        lblTurnos.setBounds(20, 740, 160, 20);

        jLabel3.setText("jLabel3");
        Eliminados.add(jLabel3);
        jLabel3.setBounds(150, 480, 37, 16);

        javax.swing.GroupLayout TableroLayout = new javax.swing.GroupLayout(Tablero);
        Tablero.setLayout(TableroLayout);
        TableroLayout.setHorizontalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );
        TableroLayout.setVerticalGroup(
            TableroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Eliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Tablero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Eliminados, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(null,"Desea rendirse? Apretar Yes para rendirse, Apretar No para seguir jugando", "Cambio de Turno", JOptionPane.YES_NO_OPTION);
        
        if (confirmacion == JOptionPane.YES_OPTION){
            String perdedor = lblTurnos1.getText().substring(10);
            String ganador="";
             
            if (perdedor.equals(datos.UsuarioLogeado)){ 
                 ganador = datos.SegundoUsuario;

              
                JOptionPane.showMessageDialog(null, ganador + " ha ganado ya que " + perdedor + 
                        " se ha retirado del juego" + " . Apretar OK para volver al menu principal"); 
                 //resultados Juegos 
          String resultado="El jugador " +ganador + " gano ya que " + perdedor + " se retiro del juego";
         datos.agregarRegistroJuego(resultado);

            }
            else {
                ganador=datos.UsuarioLogeado;
                JOptionPane.showMessageDialog(null, ganador + " ha ganado ya que " + perdedor + 
                        " se ha retirado del juego" + " . Apretar OK para volver al menu principal"); 
           //resultados Juegos
                String resultado="El jugador "+ganador + " gano ya que " + perdedor + " se retiro del juego";
         datos.agregarRegistroJuego(resultado);

            }
            
            Usuarios1 usuarioGanador = datos.buscarUsuario(ganador);
        if (usuarioGanador != null) {
            //Sumar Puntos usando Polimorfismo
            usuarioGanador.IncrementarPuntos(3);
        }       
            menu = new Menu1(login, datos);
            menu.setVisible(true);
            this.setVisible(false);
           
        }
    }//GEN-LAST:event_btnRetiroActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Eliminados;
    private javax.swing.JPanel Tablero;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTurnos;
    private javax.swing.JLabel lblTurnos1;
    private javax.swing.JTextArea txtAreaEliminados;
    // End of variables declaration//GEN-END:variables
}
