/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

import javax.swing.JOptionPane;

/**
 *
 * @author Azalia
 */
public class Menu1 extends javax.swing.JFrame {
Player datos;
    Login1 login;
    Configuracion1 configuracion;
    Reportes reportes;
    MiPerfil1 perfil;
    /**
     * Creates new form Menu1
     */
    public Menu1(Login1 login,Player datos) {
        initComponents();
        
        setLocationRelativeTo(this);
        this.login=login; 
        this.datos=datos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnJugarGhosts = new javax.swing.JButton();
        btnConfiguracion = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnMiPerfil = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Sitka Text", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 0));
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 160, 80));

        btnJugarGhosts.setBackground(new java.awt.Color(204, 153, 0));
        btnJugarGhosts.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnJugarGhosts.setText("Jugar Ghosts");
        btnJugarGhosts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJugarGhostsActionPerformed(evt);
            }
        });
        jPanel1.add(btnJugarGhosts, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        btnConfiguracion.setBackground(new java.awt.Color(204, 153, 0));
        btnConfiguracion.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnConfiguracion.setText("Configuracion");
        btnConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfiguracionActionPerformed(evt);
            }
        });
        jPanel1.add(btnConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        btnReportes.setBackground(new java.awt.Color(204, 153, 0));
        btnReportes.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnReportes.setText("Reportes");
        btnReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportesActionPerformed(evt);
            }
        });
        jPanel1.add(btnReportes, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        btnMiPerfil.setBackground(new java.awt.Color(204, 153, 0));
        btnMiPerfil.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnMiPerfil.setText("Mi Perfil");
        btnMiPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiPerfilActionPerformed(evt);
            }
        });
        jPanel1.add(btnMiPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, -1, -1));

        btnSalir.setBackground(new java.awt.Color(204, 153, 0));
        btnSalir.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnSalir.setText("Cerrar Sesion");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo menuF1.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportesActionPerformed
        // TODO add your handling code here:
       reportes=new Reportes(login,datos);
        reportes.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnReportesActionPerformed

    private void btnMiPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiPerfilActionPerformed
        // TODO add your handling code here:
         perfil=new MiPerfil1(login,datos);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMiPerfilActionPerformed

    private void btnJugarGhostsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarGhostsActionPerformed
        // TODO add your handling code here:
        SegundoPlayer1 pedirsegundo = new SegundoPlayer1(login,datos);
        pedirsegundo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnJugarGhostsActionPerformed

    private void btnConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfiguracionActionPerformed
        // TODO add your handling code here:
        configuracion=new Configuracion1(login,datos);
        configuracion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnConfiguracionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
         int respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de que quieres cerrar sesión?", "Confirmación de cierre de sesión", JOptionPane.OK_CANCEL_OPTION);
    if (respuesta == JOptionPane.OK_OPTION) {
        MenuInicio menuInicio=new MenuInicio(login,datos);
        menuInicio.setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnSalirActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfiguracion;
    private javax.swing.JButton btnJugarGhosts;
    private javax.swing.JButton btnMiPerfil;
    private javax.swing.JButton btnReportes;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
