/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1;

/**
 *
 * @author Azalia
 */
public class VerMisDatos extends javax.swing.JFrame {
    Player datos;
    Menu1 menu;
    Login1 login;
    
    /**
     * Creates new form VerMisDatos
     */
    public VerMisDatos(Login1 login,Player datos) {
        initComponents();
        setLocationRelativeTo(this);
         this.datos=datos;
        this.login=login;
        menu=new Menu1(login,datos);
        mostrarRanking();
         lblUsuarioLogeado.setText(datos.UsuarioLogeado);
    }
    
     private void mostrarRanking() {
         StringBuilder ranking = new StringBuilder();
    Usuarios1 usuarioLogeado = datos.buscarUsuario(datos.UsuarioLogeado);

    if (usuarioLogeado != null) {
        ranking.append(usuarioLogeado.getPuntos()).append(" puntos\n");
    }
    lblPuntos.setText(ranking.toString());
     }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuarioLogeado = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblUsualioLogeado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Ver Mis Datos");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 310, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText("Puntos: ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        lblUsuarioLogeado.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblUsuarioLogeado.setForeground(new java.awt.Color(0, 102, 51));
        lblUsuarioLogeado.setText("Usuario");
        getContentPane().add(lblUsuarioLogeado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        btnBack.setBackground(new java.awt.Color(153, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 0));
        jLabel5.setText("Usuario Logged In: ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        lblPuntos.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(0, 102, 0));
        lblPuntos.setText("puntos");
        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo sub sub.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 340));

        lblUsualioLogeado1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        lblUsualioLogeado1.setForeground(new java.awt.Color(0, 102, 51));
        lblUsualioLogeado1.setText("Usuario");
        getContentPane().add(lblUsualioLogeado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        MiPerfil1 perfil = new MiPerfil1(login,datos);
        perfil.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblUsualioLogeado1;
    private javax.swing.JLabel lblUsuarioLogeado;
    // End of variables declaration//GEN-END:variables
}
